---
# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: Auto-update on push
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  update_on_push_job:
    runs-on: ubuntu-latest
    name: Auto-update on push
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            github-cloud.s3.amazonaws.com:443
            lfs.github.com:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443
            release-assets.githubusercontent.com:443

      - name: Checkout Source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Generate Changelog
        uses: orhun/git-cliff-action@98c93442bb05a455a77bee982867857ae748eeea # v4.5.1
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Generate artifacts
        run: |
          # Generate list of authors
          ./scripts/generate-contributors.sh

      - name: Git commit if changed
        run: |
          git config user.name "Northwood Labs (Bot)"
          git config user.email "bot@northwood-labs.com"

          set +e

          git add .
          git status | grep modified
          if [ $? -eq 0 ]; then
            git commit -a -m "automation: Updated AUTHORS and CHANGELOG on $(date)."
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main
          fi
